/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vn.coursemanage.gui.course;

/**
 *
 * @author popu
 */
public class CourseManagerGUI extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public CourseManagerGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        onlineCourseManagerGUI2 = new vn.coursemanage.gui.course.OnlineCourseManagerGUI();
        onsiteCourseManagerGUI2 = new vn.coursemanage.gui.course.OnsiteCourseManagerGUI();

        jButton2.setText("jButton2");

        jTabbedPane1.addTab("ONLINE", onlineCourseManagerGUI2);
        jTabbedPane1.addTab("ONSITE", onsiteCourseManagerGUI2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private vn.coursemanage.gui.course.OnlineCourseManagerGUI onlineCourseManagerGUI2;
    private vn.coursemanage.gui.course.OnsiteCourseManagerGUI onsiteCourseManagerGUI2;
    // End of variables declaration//GEN-END:variables
}
